#!/bin/sh
docker network create pmc-dev_default
docker-compose up -d --remove-orphans --force-recreate --build
docker-compose run --rm build-npm
docker-compose run --rm build-php
docker-compose run --rm test-npm
docker-compose run --rm test-php
