#!/bin/sh
docker network create pmc-dev_default
docker-compose build --force-rm --compress
docker-compose run --rm pipeline-npm-build
docker-compose run --rm pipeline-composer-build
docker-compose run --rm -d wp
docker-compose run --rm pipeline-php-test

