#!/bin/sh
$COMPOSER_VENDOR_DIR/bin/phpcs --config-set default_standard "${PHPCS_STANDARD}"
$COMPOSER_VENDOR_DIR/bin/phpcs --runtime-set text_domain ${TEXT_DOMAIN} --report=json "${PHP_DIFF_FILE}" > "${PHPCS_FILE}"
$COMPOSER_VENDOR_DIR/bin/diffFilter --phpcsStrict "${PHP_DIFF_FILE}" "${PHPCS_FILE}" 100
