#!/bin/sh
coverage_filename="/tmp/coverage-${WORDPRESS_THEME}-${COMMIT}.xml"
$COMPOSER_VENDOR_DIR/bin/phpunit -v --exclude-group ${PHPUNIT_EXCLUDE_GROUPS} --coverage-clover=${coverage_filename}
$COMPOSER_VENDOR_DIR/bin/diffFilter --phpunit $COMMIT_DIFF_FILENAME ${coverage_filename}
