#!/bin/sh
mkdir -p /tmp
echo $COMMIT_DIFF
touch "${COMMIT_DIFF}"
touch "${PHP_FILES}"
# Master has different rules because it can't compare against itself and needs to only test the latest commit
if [ "master" = "$(git rev-parse --abbrev-ref HEAD)" ]
	then
		# Make a file for the commit diff to read into tests a variable is too large
		(git --no-pager diff --diff-filter=d --no-commit-id "$(git rev-parse --short HEAD^)") > "${COMMIT_DIFF}"
		(git --no-pager diff --diff-filter=d --no-commit-id --name-only "$(git rev-parse --short HEAD^)" -- '*.php') > "${PHP_FILES}"
	else
		(git --no-pager diff origin/master --diff-filter=d --no-commit-id) > "${COMMIT_DIFF}"
		(git --no-pager diff origin/master --diff-filter=d --name-only -- '*.php') > "${PHP_FILES}"
fi
