#!/bin/sh
$COMPOSER_VENDOR_DIR/bin/phpcs --config-set default_standard "${PHPCS_STANDARD}"
$COMPOSER_VENDOR_DIR/bin/phpcs --runtime-set text_domain ${TEXT_DOMAIN} --report=json $PHP_FILES > /tmp/phpcs.json
$COMPOSER_VENDOR_DIR/bin/diffFilter --phpcsStrict $COMMIT_DIFF_FILENAME /tmp/phpcs.json 100
